# A pod that will startup and do a complete coreos-assembler run
# against https://github.com/coreos/fedora-coreos-config and store
# the results in the mounted PV
apiVersion: v1
metadata:
    name: coreos-assembler
kind: Pod
spec:
  initContainers:
   # This container clones the desired git repo to the EmptyDir volume.
   - name: coreos-assembler-init
     image: docker-registry.default.svc:5000/fedora-coreos/dustymabe-coreos-assembler:latest
#    image: quay.io/dustymabe/coreos-assembler:latest
     imagePullPolicy: Always
     workingDir: /srv/
     command: ['/bin/bash']
     args: ['-c', "mkdir -p /srv/srv/; cd /srv/srv/; if [ ! -d src/config ]; then /usr/bin/coreos-assembler init https://github.com/coreos/fedora-coreos-config &>> /srv/init.log; fi" ]
     securityContext:
       privileged: false
     volumeMounts:
     - name: data
       mountPath: /srv/
   - name: coreos-assembler-git-update
     image: docker-registry.default.svc:5000/fedora-coreos/dustymabe-coreos-assembler:latest
#    image: quay.io/dustymabe/coreos-assembler:latest
     imagePullPolicy: Always
     workingDir: /srv/srv/
     command: ['/bin/bash']
     args: ['-c', "cd ./src/config && git pull &>> /srv/pull.log"]
     securityContext:
       privileged: false
     volumeMounts:
     - name: data
       mountPath: /srv/
  containers:
   - name: coreos-assembler
     image: docker-registry.default.svc:5000/fedora-coreos/dustymabe-coreos-assembler:latest
#    image: quay.io/dustymabe/coreos-assembler:latest
     imagePullPolicy: Always
     workingDir: /srv/srv/
     args:
     - build
     volumeMounts:
     - name: data
       mountPath: /srv/
     - name: duffy-key
       mountPath: /var/run/secrets/kubernetes.io/duffy-key
       readOnly: true
     securityContext:
       privileged: false
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: coreos-assembler-claim
  - name: duffy-key
    secret:
      secretName: duffy.key
  restartPolicy: Never
