credentials:
  system:
    domainCredentials:
      - credentials:
        - file:
            scope: GLOBAL
            fileName: fedora-push-registry-secret
            id: fedora-push-registry-secret
            # Secret must be base64-encoded. `${fedora-push-registry-secret/dockercfg}`
            # expands to the *contents* of that file, not its path.
            # See: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc#passing-secrets-through-variables
            secretBytes: "${base64:${fedora-push-registry-secret/dockercfg}}"
            description: Push secret for quay.io/fedora repos
